### ISSUE TITLE
Adjust color scheme for color blindness

### ISSUE THREAD

**Issue by ChrisTheDBA** [hurricane-response/michael_website#6]
the maps are difficult to read in someone is green blind. Some good color schemes for color blind are:

![image](https://user-images.githubusercontent.com/231093/46739910-93ecb580-cc6f-11e8-88c6-7f3726ceb451.png)

**Comment by ChrisTheDBA** [comment]
https://i.imgur.com/6hH7S9Z.png

**Comment by ChrisTheDBA** [comment]
![image](https://user-images.githubusercontent.com/231093/46749168-2e0a2900-cc83-11e8-8485-6e080eb05d1c.png)

**Comment by ChrisTheDBA** [comment]
The routes are difficult to see for someone with green blindness. Does not provide for enough contrast.

**Comment by miklb** [comment]
this will be resolved in the new map theme site using an updated evacuation layer in a Mapbox account we will have access to the styling on.
